// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package bitsports

type CategoryInput struct {
	Name string `json:"name"`
}

type CategoryInputUpdate struct {
	ID   int     `json:"id"`
	Name *string `json:"name"`
}

type ProductInput struct {
	Name  string  `json:"name"`
	Price float64 `json:"price"`
}

type ProductInputUpdate struct {
	ID    int      `json:"id"`
	Name  *string  `json:"name"`
	Price *float64 `json:"price"`
}

type UserInputSingIn struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserInputSingUp struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

type UserInputUpdate struct {
	Email    *string `json:"email"`
	Name     *string `json:"name"`
	Password *string `json:"password"`
}
