// Code generated by entc, DO NOT EDIT.

package ent

import "context"

func (c *Category) Products(ctx context.Context) ([]*Product, error) {
	result, err := c.Edges.ProductsOrErr()
	if IsNotLoaded(err) {
		result, err = c.QueryProducts().All(ctx)
	}
	return result, err
}

func (pr *Product) Users(ctx context.Context) ([]*User, error) {
	result, err := pr.Edges.UsersOrErr()
	if IsNotLoaded(err) {
		result, err = pr.QueryUsers().All(ctx)
	}
	return result, err
}

func (pr *Product) Categories(ctx context.Context) ([]*Category, error) {
	result, err := pr.Edges.CategoriesOrErr()
	if IsNotLoaded(err) {
		result, err = pr.QueryCategories().All(ctx)
	}
	return result, err
}

func (u *User) Products(ctx context.Context) ([]*Product, error) {
	result, err := u.Edges.ProductsOrErr()
	if IsNotLoaded(err) {
		result, err = u.QueryProducts().All(ctx)
	}
	return result, err
}
